import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

function readHtml(file) {
  return readFileSync(join(root, file), 'utf8');
}

function assertIncludes(content, expected, message) {
  assert.ok(content.includes(expected), message || `Expected to find ${expected}`);
}

assert.ok(existsSync(join(root, 'dashboard.html')), 'dashboard.html should exist');

const dashboard = readHtml('dashboard.html');
const store = readHtml('store.html') + '\n' + readHtml('store-style.css') + '\n' + readHtml('store-app.js') + '\n' + readHtml('store-delivery-note.js');

assertIncludes(store, 'html2canvas@1.4.1', 'store should load html2canvas for delivery note image generation');
assertIncludes(store, "event.stopPropagation(); generateDeliveryNote", 'history cards should generate delivery notes without opening detail');
assertIncludes(store, 'async function getDeliveryNoteRows(orderNo)', 'store should fetch and aggregate delivery note rows');
assertIncludes(store, 'function buildDeliveryNoteHtml', 'store should build a printable delivery note DOM');
assertIncludes(store, 'async function generateDeliveryNote(orderNo,orderDate)', 'store should generate a delivery note image from an order');
assertIncludes(store, 'function downloadDeliveryImage(imgUrl,fileName)', 'store should download generated delivery note images directly');
assertIncludes(store, 'function amountToChineseUpper(amount)', 'store should convert total amount to Chinese uppercase RMB');
assertIncludes(store, 'brand', 'delivery note aggregation should use product brand');
assertIncludes(store, 'spec', 'delivery note aggregation should use product spec');
assertIncludes(store, 'sale_unit', 'delivery note aggregation should support new sale unit fields');
assertIncludes(store, 'sale_qty', 'delivery note aggregation should support new sale quantity fields');
assertIncludes(store, 'sale_unit_price', 'delivery note aggregation should support new sale unit price fields');
assertIncludes(store, 'pcs_per_box', 'delivery note aggregation should split old order quantities by box size');
assertIncludes(store, 'pcs_per_case', 'delivery note aggregation should split old order quantities by case size');
assert.ok(!store.includes('delivery-note-overlay'), 'store should not render an in-page delivery note preview overlay');
assertIncludes(store, 'delivery-note-sheet', 'store should render a black and white printable delivery note sheet');
assert.ok(!store.includes('function openDeliveryImageFullscreen'), 'delivery image should not open a fullscreen preview');
assert.ok(!store.includes('requestFullscreen'), 'delivery note should not expose browser fullscreen preview');
assert.ok(!store.includes('left:-9999px'), 'delivery note capture should not render far outside the viewport');
assert.ok(!store.includes('col-note'), 'delivery note should not include a remarks column');
assert.ok(!store.includes('\\\\u5907\\\\u6ce8'), 'delivery note should not render remarks text');
assert.ok(!store.includes('deliveryOrderNo'), 'delivery note should not expose system order number in the visible template');
assert.ok(!store.includes('deliveryBarcode'), 'delivery note should not expose barcodes in the visible template');
assertIncludes(dashboard, "location.href='store_import'", 'dashboard links to store import');
assertIncludes(dashboard, "location.href='stock_import'", 'dashboard links to the unified stock import page');
assert.ok(!dashboard.includes("location.href='stock_jn'"), 'dashboard should not expose a separate JN stock import button');
assert.ok(!dashboard.includes("location.href='stock_ct'"), 'dashboard should not expose a separate CT stock import button');
assertIncludes(dashboard, "location.href='stock_summary'", 'dashboard links to stock summary');
assertIncludes(dashboard, '<strong>库存管理</strong>', 'dashboard labels stock summary as inventory management');
assert.ok(!dashboard.includes('<strong>总库存管理</strong>'), 'dashboard should not label stock summary with total inventory wording');
assertIncludes(dashboard, "location.href='products'", 'dashboard links to products table');
assertIncludes(dashboard, "location.href='employees'", 'dashboard links to employees table');
assertIncludes(dashboard, ".from('sales_orders')", 'dashboard loads sell-in orders');
assertIncludes(dashboard, ".from('employees')", 'dashboard loads employee names');
assertIncludes(dashboard, 'employeeRankRows', 'dashboard renders employee ranking');
assertIncludes(dashboard, 'id="employeeFilter"', 'dashboard should provide employee chip filter area');
assertIncludes(dashboard, 'class="employee-filter"', 'dashboard employee filter should use chip layout');
assertIncludes(dashboard, 'employee-chip', 'dashboard should render employee chips');
assertIncludes(dashboard, 'setEmployeeFilter', 'employee chips should switch selected employee');
assertIncludes(dashboard, 'selectedEmployeeCode', 'dashboard should store selected employee code');
assertIncludes(dashboard, 'function getFilteredOrders', 'dashboard should filter orders by selected employee');
assertIncludes(dashboard, 'function renderEmployeeFilter', 'dashboard should build employee chip options');
assertIncludes(dashboard, '全部员工</button>', 'dashboard employee filter should include an all option');
assertIncludes(dashboard, 'function buildMetrics(orders)', 'dashboard should rebuild metrics from filtered orders');
assertIncludes(dashboard, "['💵','卖进金额'", 'dashboard should show the sell-in amount metric');
assertIncludes(dashboard, '<th style="width:130px;">卖进金额</th>', 'employee ranking should show the sell-in amount column');
assertIncludes(dashboard, 'onclick="exportOrderExcel()"', 'dashboard should expose order export button');
assertIncludes(dashboard, '导出开单单据', 'dashboard order export button should be visible');
assertIncludes(dashboard, 'async function exportOrderExcel()', 'dashboard should implement async order item export');
assertIncludes(dashboard, "client.rpc('get_dashboard_export_order_items'", 'dashboard should request export details through one backend query');
assertIncludes(dashboard, 'p_start_at:start?start.toISOString():null', 'dashboard export should pass the selected start date to the backend');
assertIncludes(dashboard, 'p_end_at:end?end.toISOString():null', 'dashboard export should pass the selected end date to the backend');
assertIncludes(dashboard, "['开单日期','员工','员工号','门店编号','门店','规格口味','条码','整数','整价','散数','散价','金额']", 'dashboard order export should use spec/flavor item-level headers');
assertIncludes(dashboard, 'formatDateOnly(item.created_at)', 'dashboard order export should only include date precision');
assertIncludes(dashboard, "[product?.spec,product?.flavor]", 'dashboard order export should use product spec and flavor');
assertIncludes(dashboard, 'Number(item.sale_unit_price ?? item.unit_price ?? 0)', 'dashboard order export should preserve sale-unit price fallback');
assertIncludes(dashboard, 'Number(item.sale_qty ?? item.qty ?? 0)', 'dashboard order export should preserve sale-unit quantity fallback');
assertIncludes(dashboard, 'XLSX.writeFile(wb,getExportFileName(),{cellStyles:true})', 'dashboard should export the styled workbook with the selected-range filename');
assert.ok(!dashboard.includes("['开单时间', '员工', '员工号', '门店编号', '门店', '单号', '金额', '状态']"), 'dashboard export should not use order-level headers');
assert.ok(!dashboard.includes("order.order_no || ''"), 'dashboard order export should not export order number as a column');
assert.ok(!dashboard.includes("order.status || ''"), 'dashboard order export should not include status');
assert.ok(!dashboard.includes(".select('order_id, barcode, price, qty')"), 'dashboard export should not query nonexistent order_id or price fields');
assert.ok(!dashboard.includes(".in('order_id', orderIds)"), 'dashboard export should not join by nonexistent order_id');
assert.ok(!dashboard.includes('Number(item.price || 0)'), 'dashboard export should not use nonexistent item.price');
assertIncludes(dashboard, 'hideStatus();', 'dashboard should hide loaded status after rendering');
assert.ok(!dashboard.includes('已加载 ${filteredOrders.length} 张卖进单据'), 'dashboard should not show green loaded order count');
assert.ok(!dashboard.includes('employeeSearch'), 'dashboard should not use employee search input');
assert.ok(!dashboard.includes('placeholder="搜索员工名字"'), 'dashboard should not use employee name search box');
assert.ok(!dashboard.includes('filterOrdersByEmployeeName'), 'dashboard should not filter by text search');
assert.ok(!dashboard.includes('recentOrderRows'), 'dashboard should not render recent orders');
assert.ok(!dashboard.includes('最近卖进单据'), 'dashboard should remove recent orders card');
assert.ok(!dashboard.includes('<div class="split">'), 'dashboard should show ranking as the default single section');
assertIncludes(dashboard, '.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:14px}', 'dashboard should use the current three metric cards');
assert.ok(!dashboard.includes('动销人员'), 'dashboard should not show active seller metric');
assert.ok(!dashboard.includes('activeSellerCount'), 'dashboard should not compute active seller metric');
assert.ok(!dashboard.includes('<div class="hint">元</div>'), 'dashboard metric cards should not show small unit hints');
assert.ok(!dashboard.includes('<div class="hint">有效订单数</div>'), 'dashboard order metric should not show small hint');
assert.ok(!dashboard.includes('<div class="hint">有卖进的门店</div>'), 'dashboard store metric should not show small hint');
assert.ok(!dashboard.includes('<div class="hint">元 / 单</div>'), 'dashboard average metric should not show small hint');
assert.ok(!dashboard.includes('<div class="sub">${esc(row.employee_code)}</div>'), 'employee ranking should not show employee code subtitle');
assert.ok(!dashboard.includes('<div class="sub">${esc(order.employee_code || \'\')}</div>'), 'recent orders should not show employee code subtitle');

const employees = readHtml('employees.html');
assert.ok(!employees.includes('sortModeBtn'), 'employees page should not have a sort button');
assert.ok(!employees.includes('toggleSortMode'), 'employees page should not implement sorting');
assertIncludes(employees, ".from('dealer_employee_mappings')", 'employees page should load dealer employee mappings');
assertIncludes(employees, 'customer_code', 'employees page should read mapping customer_code');
assertIncludes(employees, 'saveMappingForEmployee', 'employees page should save mapping customer codes');
assertIncludes(employees, 'renderCustomerCodeInput', 'employees page should render editable customer codes');
assertIncludes(employees, '经销商客户编号', 'employees page should label customer_code as dealer customer code');

const headerMatch = employees.match(/<thead>[\s\S]*?<tr>([\s\S]*?)<\/tr>/);
assert.ok(headerMatch, 'employees table should have a header row');
const headerText = headerMatch[1].replace(/\s+/g, ' ');
const codeIndex = headerText.indexOf('employee-code-col');
const nameIndex = headerText.indexOf('employee-name-col');
const customerCodeIndex = headerText.indexOf('customer-code-col');
const activeIndex = headerText.indexOf('active-col');
assert.ok(codeIndex >= 0, 'employee code column should exist');
assert.ok(nameIndex > codeIndex, 'employee name should be after employee code');
assert.ok(customerCodeIndex > nameIndex, 'dealer customer code should be after employee name');
assert.ok(!headerText.includes('action-col'), 'employee table should not keep a separate action column');
assert.ok(activeIndex > customerCodeIndex, 'active column should be the rightmost employee column');

const newRowMatch = employees.match(/function renderNewEmployeeRow\(\)[\s\S]*?return `([\s\S]*?)`;/);
assert.ok(newRowMatch, 'new employee row renderer should exist');
const newRow = newRowMatch[1];
assert.ok(newRow.indexOf('new_employee_code') < newRow.indexOf('new_name'), 'new row code should be before name');
assert.ok(newRow.indexOf('new_name') < newRow.indexOf('new_customer_code'), 'new row dealer customer code should be after name');
assert.ok(newRow.indexOf('new_customer_code') < newRow.indexOf('inline-actions'), 'new row actions should be after dealer customer code');
assert.ok(newRow.indexOf('inline-actions') < newRow.indexOf('new_is_active'), 'new row active checkbox should be rightmost');

const renderTableMatch = employees.match(/function renderTable\(\)[\s\S]*?const rows = filtered\.map\(e => `([\s\S]*?)`\)\.join/);
assert.ok(renderTableMatch, 'employee table row renderer should exist');
const dataRow = renderTableMatch[1];
assert.ok(dataRow.indexOf("renderInput(e,'employee_code')") < dataRow.indexOf("renderInput(e,'name')"), 'data row code should be before name');
assert.ok(dataRow.indexOf("renderInput(e,'name')") < dataRow.indexOf('renderCustomerCodeInput'), 'data row dealer customer code should be after name');
assert.ok(!dataRow.includes('saveRow'), 'data row should not keep per-row save actions');
assert.ok(dataRow.indexOf('renderCustomerCodeInput') < dataRow.indexOf('data-field="is_active"'), 'data row active checkbox should be rightmost');

const stockImport = readHtml('stock_import.html');
const stockImportPage = readHtml('src/stock-import/StockImportPage.tsx');
const dealerImportDomain = readHtml('src/domain/dealer-outbound-import.ts');
const dealerImportRepository = readHtml('src/services/dealer-outbound-import-repository.ts');
const storeImport = readHtml('store_import.html');
const storeImportPage = readHtml('src/store-import/StoreImportPage.tsx');
assertIncludes(storeImport, '--primary:#4A154B', 'store import should use the stock import primary color');
assertIncludes(storeImportPage, 'className="container"', 'store import should use the shared import container');
assertIncludes(storeImportPage, 'className="card"', 'store import should use the shared import card');
assertIncludes(storeImportPage, "className={`upload-box", 'store import should use the shared upload box');
assertIncludes(storeImportPage, 'className="btn-submit"', 'store import should use the shared submit button');
assert.ok(!(storeImport + storeImportPage).includes('数据清洗'), 'store import should not mention data cleaning');
assert.ok(!(storeImport + storeImportPage).includes('差集'), 'store import should not mention set-difference import');
assert.ok(!(storeImport + storeImportPage).includes('覆盖'), 'store import should not mention overwrite behavior in visible copy');
assertIncludes(storeImport, 'src="/src/store-import/main.tsx"', 'store import should mount its React TypeScript entry');
assertIncludes(storeImportPage, '点击选择文件，或将门店 Excel 文件拖拽至此处', 'store import should keep the upload prompt');
assertIncludes(storeImportPage, '>\n          导入\n        </button>', 'store import should keep the visible import button copy');
assertIncludes(stockImport, 'src="/src/stock-import/main.tsx"', 'stock import should mount its React TypeScript entry');
assertIncludes(stockImportPage, 'className="import-grid"', 'stock import should render both dealer import components side by side');
assertIncludes(stockImportPage, "title: '吉能'", 'stock import should include the JN import component');
assertIncludes(stockImportPage, "title: '长涛'", 'stock import should include the CT import component');
assertIncludes(stockImportPage, 'A单号、C制单日期、D客户编号、E客户、G条形码、H商品名称、I包装、J件、L散', 'stock import should keep JN fixed import rules');
assertIncludes(stockImportPage, 'A制单日期、C商品名称、D包装、F件、G散、Q客户编号、R客户名称、X单号、AA条形码', 'stock import should keep CT fixed import rules');
assertIncludes(dealerImportDomain, "prefix: 'JN'", 'stock import should keep JN import configuration');
assertIncludes(dealerImportDomain, "prefix: 'CT'", 'stock import should keep CT import configuration');
assertIncludes(dealerImportRepository, "from('raw_dealer_outbounds')", 'stock import should continue writing dealer outbound rows');
assert.ok(!storeImport.includes('fixed-map'), 'store import should not show stock fixed-column rules');

assert.ok(existsSync(join(root, 'stock_summary.html')), 'stock_summary.html should exist');
assert.ok(existsSync(join(root, 'stock_summary-legacy.html')), 'stock_summary-legacy.html should exist');
const stockSummaryEntry = readHtml('stock_summary.html');
const stockSummary = readHtml('stock_summary-legacy.html');
assertIncludes(stockSummary, '<title>库存管理</title>', 'stock summary page title should be inventory management');
assertIncludes(stockSummary, '<h1>库存管理</h1>', 'stock summary page heading should be inventory management');
assertIncludes(stockSummary, 'onclick="exportEmployeeStocks()"', 'stock summary should expose export button');
assertIncludes(stockSummary, "['员工名字','员工号','规格口味','条码','库存散数']", 'stock export should use spec/flavor headers with barcode');
assertIncludes(stockSummary, "item.product_barcode", 'stock export should include product barcode values');
assertIncludes(stockSummary, 'function exportEmployeeStocks()', 'stock summary should implement employee stock export');
assertIncludes(stockSummary, 'xlsx.full.min.js', 'stock export should load the xlsx writer');
assertIncludes(stockSummary, 'XLSX.writeFile', 'stock export should write a real xlsx file');
assertIncludes(stockSummary, '库存管理_${new Date().toISOString().slice(0,10)}.xlsx', 'stock export filename should use .xlsx');
assertIncludes(stockSummary, '.detail-table{min-width:1040px;table-layout:fixed}', 'stock detail table should use fixed layout');
assertIncludes(stockSummary, '.detail-table th,.detail-table td{padding:9px 10px;vertical-align:top;line-height:1.45}', 'stock detail table cells should top-align with readable line height');
assertIncludes(stockSummary, '.detail-product', 'stock detail product names should use a dedicated style');
assertIncludes(stockSummary, '<td colspan="6">', 'stock summary detail row should span the simplified six-column table');
assertIncludes(stockSummary, 'hideStatus();', 'stock summary should hide the green loaded status after rendering');
assert.ok(!stockSummary.includes('有车存员工'), 'stock summary should use inventory wording instead of vehicle-stock wording');
assert.ok(!stockSummary.includes('需要重点核对'), 'stock summary should not show the negative-stock hint');
assert.ok(!stockSummary.includes('<th>主要库存</th>'), 'stock summary should not show main inventory column');
assert.ok(!stockSummary.includes('row.topItems'), 'stock summary should not compute or render main inventory text');
assert.ok(!stockSummary.includes('<div class="sub">${esc(row.employee_code)}'), 'stock summary should not show employee code below name');
assert.ok(!stockSummary.includes('application/vnd.ms-excel'), 'stock export should not use HTML-as-XLS mime type');
assert.ok(!stockSummary.includes('link.download = `库存管理_${stamp}.xls`'), 'stock export should not download fake .xls files');
assert.ok(!stockSummary.includes('复制核对清单'), 'stock summary should not show copy checklist');
assert.ok(!stockSummary.includes('toggleCopyText'), 'stock summary should remove copy checklist behavior');
assert.ok(!stockSummary.includes('copyArea'), 'stock summary should remove copy checklist textarea');
assert.ok(!stockSummary.includes('<div class="label">库存品项</div>'), 'stock summary should not show large product item metric');
assert.ok(!stockSummary.includes('<div class="label">总散数</div>'), 'stock summary should not show large total loose quantity metric');
assert.ok(!stockSummary.includes('${esc(item.product.sub)}'), 'stock detail should not show brand/spec/flavor subtitle');
assertIncludes(stockSummaryEntry, 'id="root"', 'stock summary primary entry should mount React');
assertIncludes(stockSummaryEntry, 'src="/src/stock-summary/main.tsx"', 'stock summary primary entry should load the React module');
assert.ok(!stockSummaryEntry.includes("client.rpc('import_van_stock_baseline'"), 'stock summary entry should not retain inline Supabase calls');
