-- Supabase database documentation export
-- Project: new (wyjbnnqhiehjccmojbbg)
-- Schema: public
-- Object type: tables
-- Generated at: 2026-06-21 01:15:42 +08
-- Note: Documentation DDL only. Do not run blindly as a migration.

CREATE TABLE public.dealer_employee_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  customer_code text NOT NULL,
  customer_name text,
  employee_code text,
  CONSTRAINT dealer_employee_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT dealer_employee_mappings_customer_code_key UNIQUE (customer_code)
);

CREATE TABLE public.employee_store_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'::text),
  employee_code text NOT NULL,
  atom_code text NOT NULL,
  store_name text NOT NULL,
  is_active boolean DEFAULT true,
  CONSTRAINT employee_store_assets_pkey PRIMARY KEY (id),
  CONSTRAINT employee_store_assets_customer_code_key UNIQUE (atom_code)
);

CREATE TABLE public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  employee_code text NOT NULL,
  name text NOT NULL,
  is_active boolean DEFAULT true,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_employee_code_key UNIQUE (employee_code)
);

CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  barcode text NOT NULL,
  name text NOT NULL,
  brand text,
  spec text,
  flavor text,
  default_price numeric DEFAULT 0,
  pcs_per_case numeric DEFAULT 1,
  pcs_per_box numeric DEFAULT 1,
  is_active boolean DEFAULT true,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_barcode_key UNIQUE (barcode)
);

CREATE TABLE public.raw_dealer_outbounds (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  order_no text,
  doc_no text,
  bill_date text,
  customer_code text,
  customer_name text,
  sku_code text,
  barcode text,
  product_name text,
  package_reg numeric,
  qty_piece numeric,
  amount_piece numeric,
  qty_scatter numeric,
  unit text,
  unit_price numeric,
  discount numeric,
  total_amount numeric,
  is_processed boolean DEFAULT false,
  import_batch_id text,
  is_triple_spec_direct boolean DEFAULT false,
  CONSTRAINT raw_dealer_outbounds_pkey PRIMARY KEY (id),
  CONSTRAINT unique_order_item UNIQUE (order_no, barcode)
);

CREATE TABLE public.sales_order_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  order_no text NOT NULL,
  barcode text NOT NULL,
  product_name text,
  qty numeric NOT NULL,
  unit_price numeric NOT NULL,
  amount numeric NOT NULL,
  remark text,
  CONSTRAINT sales_order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE public.sales_orders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  order_no text NOT NULL,
  employee_code text NOT NULL,
  atom_code text NOT NULL,
  store_name text,
  total_amount numeric DEFAULT 0,
  status text DEFAULT 'completed'::text,
  remark text,
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_order_no_key UNIQUE (order_no)
);

CREATE TABLE public.temp_upload_assets (
  employee_code text,
  atom_code text,
  store_name text
);

CREATE TABLE public.van_stocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  employee_code text,
  product_barcode text,
  qty bigint NOT NULL DEFAULT 0,
  CONSTRAINT van_stocks_pkey PRIMARY KEY (id),
  CONSTRAINT unique_employee_product_stock UNIQUE (employee_code, product_barcode)
);
